name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up CMake
      uses: actions/setup-cmake@v3
      
    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        if (-not $?) {
          Write-Error "CMake configuration failed"
          exit 1
        }
      shell: pwsh
      
    - name: Build
      run: |
        cmake --build build --config Release
        if (-not $?) {
          Write-Error "Build failed"
          exit 1
        }
      shell: pwsh
      
    - name: Get current date
      id: date
      shell: pwsh
      run: |
        $date = Get-Date -Format "yyyy-MM-dd HH:mm"
        echo "date=$date" >> $env:GITHUB_OUTPUT
      
    - name: Check Build Output
      shell: pwsh
      run: |
        $exePath = Get-ChildItem "build/Release/*.exe" | Select-Object -First 1
        if (-not $exePath) {
          Write-Error "No .exe file found in build/Release/"
          exit 1
        }
        echo "EXE_PATH=$($exePath.FullName)" >> $env:GITHUB_ENV
        
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TranslucentSM-Nightly
        path: ${{ env.EXE_PATH }}
        retention-days: 1
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.date.outputs.date }}
        release_name: Nightly ${{ steps.date.outputs.date }}
        draft: false
        prerelease: true
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.EXE_PATH }}
        asset_name: TranslucentSM-Nightly.exe
        asset_content_type: application/octet-stream