name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up CMake
      uses: actions/setup-cmake@v3
      
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TranslucentSM-Nightly
        path: build/Release/*.exe
        retention-days: 1