name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        choco install cmake --yes
        choco install visualstudio2019-workload-vctools --yes

    - name: Install dependencies
      run: |
        # 安装项目所需的依赖项
        # 如果有其他依赖项，请在此处添加安装命令
        choco install <dependency-name> --yes

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cmake --build build --config Release || exit 1

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact-windows
        path: ${{ github.workspace }}/build/Release/TranslucentSM-Legacy-Reborn.exe

    - name: Upload to release
      id: upload-release
      uses: softprops/action-gh-release@v1.10.0
      with:
        files: ${{ github.workspace }}/build/Release/TranslucentSM-Legacy-Reborn.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        overwrite: true

    - name: Cleanup
      if: always()
      run: |
        rm -rf build